### ISSUE TITLE
Determine API queries and object forms required for user stories

### ISSUE THREAD

**Issue by reevejohnson** [Hibbarcd/Project1#12]
## User Story
As a user, I want to be able to search for news and videos related to a topic of interest and compare them together in one convenient location.

## Acceptance Criteria
- [x] Research Youtube API
- [x] Research CNN API
- [x] Slack out necessary information for Youtube & CNN queries.
- [x] Add appropriate AJAX request code to the script JavaScript file.

**Comment by chrisgud** [comment]
Documentation links were slacked I believe, the choice of query strings are in our master and branches now too
