### ISSUE TITLE
Implement embedded youtube object to display results

### ISSUE THREAD

**Issue by reevejohnson** [Hibbarcd/Project1#14]
## User Story
As a user, I want to be able to search for news and videos related to a topic of interest and compare them together in one convenient location.

## Acceptance Criteria
- [x] Use link as a reference https://developers.google.com/youtube/v3/
- [x] Define a JavaScript function that puts matched news article with video in the table

**Comment by chrisgud** [comment]
Uses a bootstrap row instead of an html table but look at the video-api branch
