### ISSUE TITLE
Logically obtain news information based on user submission

### ISSUE THREAD

**Issue by reevejohnson** [Hibbarcd/Project1#15]
## User Story
As a user, I want to be able to search for news and videos related to a topic of interest and compare them together in one convenient location.

## Acceptance Criteria
- [x] Pull articles from News API based on search term.
- [x] Determine which words from headline will go into the YouTube search.
- [x] Set limit on search result. I.e only show 15 results.
- [x] Push key words from headline into an AJAX call from the YouTube API.

**Comment by chrisgud** [comment]
Stuck on authentication with youtube API!

**Comment by chrisgud** [comment]
Resolved!
