### ISSUE TITLE
Display marks on map object with tweet location information

### ISSUE THREAD

**Issue by reevejohnson** [Hibbarcd/Project1#16]
## User Story
As a user, I want to be able to filter tweets by location so I can understand what people are saying in a specific geographic area.

## Acceptance Criteria
- [ ] Research Google Maps API for how to add location marker to a generated map.
- [ ] Convert the array of locations of Tweets into location markers.

**Comment by chrisgud** [comment]
This seems vestigial! Suggest closing/remove or changing it
