### ISSUE TITLE
Logically obtain video information based on news information

### ISSUE THREAD

**Issue by reevejohnson** [Hibbarcd/Project1#25]
## User Story
As a user, I want to be able to search for news and videos related to a topic of interest and compare them together in one convenient location.

## Assessment Criteria
- [x] Pull videos from YouTube API into the object.
- [x] Pair them appropriately with the articles.

**Comment by chrisgud** [comment]
This is accomplished in the video-api branch.  There wasn't a great way I could see to truly async or batch the youtube API requests so the page will load a little slow with searches but not that bad
